### ISSUE TITLE
Not able to run autoIGV1.5.py!

### ISSUE THREAD

**Issue by Eteleeb** [michael-weinstein/autoIGV#5]
HI Michael, 

I am trying to use your autoIGV tool but I am receiving this error

```
 File "autoIGV1.5.py", line 241
    def await(igv, expectedresponse = ''):  #the second argument here is optional, and is only going to be supplied if the goal is to get a specific response from IVG (probably echo).  IGV usually responds "OK" when a command is completed or with Error:(Message) when a command fails.
            ^
SyntaxError: invalid syntax
```
I am not sure what is missing. I did follow all instructions as you posted. Is this because of a different version of python?. I am using python3.7. Any help will be appreciated. 

Thank you. 

-Abdallah

**Comment by michael-weinstein** [comment]
Python 3.7 is definitely not the version of python I initially made this for, but I don't think that should be the issue here.  I didn't realize people were still using this.

Having just run a quick google search, I know what the issue is: await was previously nothing special, but with python trying to add in better support for async operations, await became a reserved word.  With 3.4 (which is what I wrote this on) that was not an issue.  With enhanced async functionality, my function name is now a reserved word.

Gimme a minute.

**Comment by michael-weinstein** [comment]
Ok, did some cleanup on the file and renamed the function and its references.  Please try using the current version and let me know if this resolves it.

I guess I should probably clean up this code a bit if people are still using it.

Out of curiosity, what are you using this program for/what are you studying?

**Comment by Eteleeb** [comment]
Thank you so much. Will try and let you know. 

As part of our QC analyses, we perform a variant checking analysis where we look at a number of variants in a number of samples (usually > 100). Most of our studies are related to Alzheimer's disease. 

Thank you. 

-A
